### ISSUE TITLE
Set up React Native for Android 

### ISSUE THREAD

**Issue by heron2014** [brainsandbrawns/ff#1]
### TODO
- [x] Setting up a react-native project.
- [x] Add eslint for the project
- [x] Install unit testing utilities and code coverage tools.
- [x] Install mocks with which we test react-native components.
- [x] Configuring all the utilities and tools.
- [x] Example unit test.
- [x] Running your unit tests.

**Comment by heron2014** [comment]
Set up testing environment with mocha, enzyme, chai:
- ``npm install --save-dev mocha chai enzyme istanbul@1.0.0-alpha.2```

  **Mocha** : Test framework and runner. 
  **Chai** : Assertion library. 
  **Enzyme** : A utility library used to shallow render React and React Native components. 
  **Istanbul** : A code coverage generator that works well with mocha. We explicitly use the @1.0.0-    alpha.2 version which supports JSX.
- ```npm install react-dom react-native-mock --save-dev```
-  create a file .babelrc (we don't need to install babel, tt comes with React Native )and type following: 
  ```js
  {
  "presets": [ "react-native" ]
  }
  ```
- create mocha.opts file with the following:
  ```js 
   --require node_modules/babel-core/register
   --require ./test/setup.js
  ```
-  create test folder in a root of the project , then create inside of it setup.js

  ```js
   'use strict';

  import chai from 'chai';
  require('react-native-mock/mock.js');

  global.expect = chai.expect;
  ```

- package.json
  ```js
  "test": "node_modules/.bin/istanbul cover node_modules/mocha/bin/_mocha -- --opts mocha.opts --recursive ./test/**/*.spec.js",
  ```

**Comment by heron2014** [comment]
Resolved by #4
